version: '3.3'

services:
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "bootstrap-server"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"